# docker-compose.yml
version: '3.1'
name: test-safra

services:
  mongo:
    image: mongo
    restart: always
    command: [--auth]
    environment:
      MONGO_INITDB_ROOT_USERNAME: mdcarmo
      MONGO_INITDB_ROOT_PASSWORD: teste123
      MONGO_INITDB_DATABASE: expense-management-db
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: teste123
      ME_CONFIG_MONGODB_URL: mongodb://mdcarmo:teste123@mongo:27017/
volumes:
  mongodb_data_container: